# Generated by Django 3.2.4 on 2021-06-22 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_alter_perfil_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
    ]
