# Generated by Django 3.2.4 on 2021-06-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao_curta',
            field=models.TextField(max_length=255, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_longa',
            field=models.TextField(verbose_name='Descrição Longa'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(default=0, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(default=0, verbose_name='Preço Promocional'),
        ),
    ]
