# Generated by Django 3.2.4 on 2021-06-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_auto_20210614_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
