# Generated by Django 3.2.4 on 2021-06-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_auto_20210627_1605'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
